### Email Sign UP
POST http://localhost:3400/auth/email-signup
Content-Type: application/json

{
    "email": "jay@email.com",
    "password":"fhkjlknslnds"
}

### Email login

POST http://localhost:3400/auth/email-login
Content-Type: application/json

{
    "email": "jay@email.com",
    "password":"fhkjlknslnds"
}

### Google Sign up / Login
POST http://localhost:3400/auth/google-auth
Content-Type: application/json

{
    "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRjNjI2MmYzZTk3NzIzOWMwMDUzY2ViODY0Yjc3NDBmZjMxZmNkY2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXN0YXRlLW1hbmFnZXIyMDI1IiwiYXVkIjoiZXN0YXRlLW1hbmFnZXIyMDI1IiwiYXV0aF90aW1lIjoxNzQwNDEyNzExLCJ1c2VyX2lkIjoiRXBmQ0hpc0daVWhhZE5FUThKTFNwN1hzV3REMyIsInN1YiI6IkVwZkNIaXNHWlVoYWRORVE4SkxTcDdYc1d0RDMiLCJpYXQiOjE3NDA0MTI3MTEsImV4cCI6MTc0MDQxNjMxMSwiZW1haWwiOiJqYXlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImpheUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.OQFIRdAVBdehW1ry8BWlAT9VUl6G0HIxzCDTwb1GB_IrU3aDy2duEr4nE4bapQQKj3SmZnM99Fv1yyaksTUFZk-Hlah-n9r8KagHpxszSsBX7QctajbQNVb1YrpsouuXIttAfzCul2sQxoFEOy1kvSsSkjKy_De2Z-KfW6oHFA9Euje4HK06bOp08LmEsyVbCksFg0np9T3f2mdlLeQ-OoZ2Ym6NAdKY5xJR24VOUByiQXFVeWT-TuTQojudzn4j9m3FVLwBBYDXY_caoC8gJaM-i1yWHEuV8N40ViD9V7bTh6WRsS8yiw1m5uICUt9M28MFfZeZf2N7jQtgKsSu0g"
}


### Facebook Sign up / login
POST https://estateapi.torama.ng/auth/facebook-auth
Content-Type: application/json

{
    "idToken": ""
}



### Session login

POST http://localhost:3400/auth/session-login
Content-Type: application/json

{
    "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRjNjI2MmYzZTk3NzIzOWMwMDUzY2ViODY0Yjc3NDBmZjMxZmNkY2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXN0YXRlLW1hbmFnZXIyMDI1IiwiYXVkIjoiZXN0YXRlLW1hbmFnZXIyMDI1IiwiYXV0aF90aW1lIjoxNzQwNDEyNzExLCJ1c2VyX2lkIjoiRXBmQ0hpc0daVWhhZE5FUThKTFNwN1hzV3REMyIsInN1YiI6IkVwZkNIaXNHWlVoYWRORVE4SkxTcDdYc1d0RDMiLCJpYXQiOjE3NDA0MTI3MTEsImV4cCI6MTc0MDQxNjMxMSwiZW1haWwiOiJqYXlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImpheUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.OQFIRdAVBdehW1ry8BWlAT9VUl6G0HIxzCDTwb1GB_IrU3aDy2duEr4nE4bapQQKj3SmZnM99Fv1yyaksTUFZk-Hlah-n9r8KagHpxszSsBX7QctajbQNVb1YrpsouuXIttAfzCul2sQxoFEOy1kvSsSkjKy_De2Z-KfW6oHFA9Euje4HK06bOp08LmEsyVbCksFg0np9T3f2mdlLeQ-OoZ2Ym6NAdKY5xJR24VOUByiQXFVeWT-TuTQojudzn4j9m3FVLwBBYDXY_caoC8gJaM-i1yWHEuV8N40ViD9V7bTh6WRsS8yiw1m5uICUt9M28MFfZeZf2N7jQtgKsSu0g"
}

### Get user

GET http://localhost:3400/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRjNjI2MmYzZTk3NzIzOWMwMDUzY2ViODY0Yjc3NDBmZjMxZmNkY2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXN0YXRlLW1hbmFnZXIyMDI1IiwiYXVkIjoiZXN0YXRlLW1hbmFnZXIyMDI1IiwiYXV0aF90aW1lIjoxNzQwNDEyNzExLCJ1c2VyX2lkIjoiRXBmQ0hpc0daVWhhZE5FUThKTFNwN1hzV3REMyIsInN1YiI6IkVwZkNIaXNHWlVoYWRORVE4SkxTcDdYc1d0RDMiLCJpYXQiOjE3NDA0MTI3MTEsImV4cCI6MTc0MDQxNjMxMSwiZW1haWwiOiJqYXlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImpheUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.OQFIRdAVBdehW1ry8BWlAT9VUl6G0HIxzCDTwb1GB_IrU3aDy2duEr4nE4bapQQKj3SmZnM99Fv1yyaksTUFZk-Hlah-n9r8KagHpxszSsBX7QctajbQNVb1YrpsouuXIttAfzCul2sQxoFEOy1kvSsSkjKy_De2Z-KfW6oHFA9Euje4HK06bOp08LmEsyVbCksFg0np9T3f2mdlLeQ-OoZ2Ym6NAdKY5xJR24VOUByiQXFVeWT-TuTQojudzn4j9m3FVLwBBYDXY_caoC8gJaM-i1yWHEuV8N40ViD9V7bTh6WRsS8yiw1m5uICUt9M28MFfZeZf2N7jQtgKsSu0g



### Create Estate

POST http://localhost:3100/estates/create
Content-Type: application/json

{
    "name": "Peace Estate",
    "ownerId": "3"
}

### Query database
GET http://localhost:3100/ai/query-database?model=chatgpt&query=Find%20all%20users%20who%20registered%20in%20the%20last%207%20days


### Analyze industry trends
GET http://localhost:3100/ai/analyze-trends?model=chatgpt&prompt=The%20Future%20of%20AI%20in%20Healthcare


###Search web
GET http://localhost:3100/ai/search-web?query=Latest%20AI%20trends%202025